-- 工艺文件详细内容表（存储表单数据）
CREATE TABLE IF NOT EXISTS `process_file_detail` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `file_id` bigint NOT NULL COMMENT '工艺文件ID',
  `file_no` varchar(50) NOT NULL COMMENT '工艺文件编号（冗余）',
  
  -- 基本信息
  `product_model` varchar(100) DEFAULT NULL COMMENT '产品型号',
  `product_name` varchar(200) DEFAULT NULL COMMENT '产品名称',
  `mold_manufacturing_company` varchar(200) DEFAULT NULL COMMENT '模具制造公司',
  `part_name` varchar(200) DEFAULT NULL COMMENT '零件名称',
  `project_leader` varchar(50) DEFAULT NULL COMMENT '项目负责人',
  
  -- 材料信息
  `material_name` varchar(100) DEFAULT NULL COMMENT '材料名称',
  `material_grade` varchar(100) DEFAULT NULL COMMENT '材料牌号',
  `material_color` varchar(50) DEFAULT NULL COMMENT '材料颜色',
  `pigment_name` varchar(100) DEFAULT NULL COMMENT '颜料名称',
  `pigment_ratio` decimal(5,2) DEFAULT NULL COMMENT '颜料比例(%)',
  `part_net_weight` decimal(10,2) DEFAULT NULL COMMENT '零件净重(g)',
  `part_gross_weight` decimal(10,2) DEFAULT NULL COMMENT '零件毛重(g)',
  `consumption_quota` decimal(10,2) DEFAULT NULL COMMENT '消耗定额(g)',
  
  -- 模具信息
  `mold_number` varchar(100) DEFAULT NULL COMMENT '模具编号',
  `cavity_quantity` int DEFAULT NULL COMMENT '型腔数量',
  `clamping_force` decimal(10,2) DEFAULT NULL COMMENT '锁模力(Mpa)',
  
  -- 产品关键尺寸
  `product_key_dimensions` text COMMENT '产品关键尺寸（文本）',
  
  -- 设备信息
  `equipment_id` bigint DEFAULT NULL COMMENT '设备ID',
  `equipment_no` varchar(50) DEFAULT NULL COMMENT '设备编号（冗余）',
  `machine_no` varchar(50) DEFAULT NULL COMMENT '机台号（冗余）',
  `equipment_name` varchar(200) DEFAULT NULL COMMENT '设备名称/规格',
  
  -- 注塑成型工艺参数（合模、射胶、保压）
  `clamp1_pressure` decimal(10,2) DEFAULT NULL COMMENT '合模1压力(bar)',
  `clamp1_flow` decimal(5,2) DEFAULT NULL COMMENT '合模1流量(%)',
  `clamp1_position` decimal(10,2) DEFAULT NULL COMMENT '合模1位置(mm)',
  `clamp2_pressure` decimal(10,2) DEFAULT NULL COMMENT '合模2压力(bar)',
  `clamp2_flow` decimal(5,2) DEFAULT NULL COMMENT '合模2流量(%)',
  `clamp2_position` decimal(10,2) DEFAULT NULL COMMENT '合模2位置(mm)',
  `mold_protection_pressure` decimal(10,2) DEFAULT NULL COMMENT '模保压力(bar)',
  `mold_protection_flow` decimal(5,2) DEFAULT NULL COMMENT '模保流量(%)',
  `mold_protection_position` decimal(10,2) DEFAULT NULL COMMENT '模保位置(mm)',
  `high_pressure_pressure` decimal(10,2) DEFAULT NULL COMMENT '高压压力(bar)',
  `high_pressure_flow` decimal(5,2) DEFAULT NULL COMMENT '高压流量(%)',
  `high_pressure_position` decimal(10,2) DEFAULT NULL COMMENT '高压位置(mm)',
  `core_pull1_in_pressure` decimal(10,2) DEFAULT NULL COMMENT '进芯一压力(bar)',
  `core_pull1_in_flow` decimal(5,2) DEFAULT NULL COMMENT '进芯一流量(%)',
  `core_pull1_in_position` decimal(10,2) DEFAULT NULL COMMENT '进芯一位置(mm)',
  `core_pull2_in_pressure` decimal(10,2) DEFAULT NULL COMMENT '进芯二压力(bar)',
  `core_pull2_in_flow` decimal(5,2) DEFAULT NULL COMMENT '进芯二流量(%)',
  `core_pull2_in_position` decimal(10,2) DEFAULT NULL COMMENT '进芯二位置(mm)',
  `injection1_pressure` decimal(10,2) DEFAULT NULL COMMENT '射胶一段压力(bar)',
  `injection1_flow` decimal(5,2) DEFAULT NULL COMMENT '射胶一段流量(%)',
  `injection1_position` decimal(10,2) DEFAULT NULL COMMENT '射胶一段位置(mm)',
  `injection2_pressure` decimal(10,2) DEFAULT NULL COMMENT '射胶二段压力(bar)',
  `injection2_flow` decimal(5,2) DEFAULT NULL COMMENT '射胶二段流量(%)',
  `injection2_position` decimal(10,2) DEFAULT NULL COMMENT '射胶二段位置(mm)',
  `injection3_pressure` decimal(10,2) DEFAULT NULL COMMENT '射胶三段压力(bar)',
  `injection3_flow` decimal(5,2) DEFAULT NULL COMMENT '射胶三段流量(%)',
  `injection3_position` decimal(10,2) DEFAULT NULL COMMENT '射胶三段位置(mm)',
  `injection4_pressure` decimal(10,2) DEFAULT NULL COMMENT '射胶四段压力(bar)',
  `injection4_flow` decimal(5,2) DEFAULT NULL COMMENT '射胶四段流量(%)',
  `injection4_position` decimal(10,2) DEFAULT NULL COMMENT '射胶四段位置(mm)',
  `injection5_pressure` decimal(10,2) DEFAULT NULL COMMENT '射胶五段压力(bar)',
  `injection5_flow` decimal(5,2) DEFAULT NULL COMMENT '射胶五段流量(%)',
  `injection5_position` decimal(10,2) DEFAULT NULL COMMENT '射胶五段位置(mm)',
  `injection6_pressure` decimal(10,2) DEFAULT NULL COMMENT '射胶六段压力(bar)',
  `injection6_flow` decimal(5,2) DEFAULT NULL COMMENT '射胶六段流量(%)',
  `injection6_position` decimal(10,2) DEFAULT NULL COMMENT '射胶六段位置(mm)',
  `holding1_pressure` decimal(10,2) DEFAULT NULL COMMENT '保压一段压力(bar)',
  `holding1_flow` decimal(5,2) DEFAULT NULL COMMENT '保压一段流量(%)',
  `holding1_position` decimal(10,2) DEFAULT NULL COMMENT '保压一段位置(mm)',
  `holding2_pressure` decimal(10,2) DEFAULT NULL COMMENT '保压二段压力(bar)',
  `holding2_flow` decimal(5,2) DEFAULT NULL COMMENT '保压二段流量(%)',
  `holding2_position` decimal(10,2) DEFAULT NULL COMMENT '保压二段位置(mm)',
  `holding3_pressure` decimal(10,2) DEFAULT NULL COMMENT '保压三段压力(bar)',
  `holding3_flow` decimal(5,2) DEFAULT NULL COMMENT '保压三段流量(%)',
  `holding3_position` decimal(10,2) DEFAULT NULL COMMENT '保压三段位置(mm)',
  
  -- 开模、抽芯、熔胶、顶出参数
  `open_mold1_pressure` decimal(10,2) DEFAULT NULL COMMENT '开模1压力(bar)',
  `open_mold1_flow` decimal(5,2) DEFAULT NULL COMMENT '开模1流量(%)',
  `open_mold1_position` decimal(10,2) DEFAULT NULL COMMENT '开模1位置(mm)',
  `open_mold2_pressure` decimal(10,2) DEFAULT NULL COMMENT '开模2压力(bar)',
  `open_mold2_flow` decimal(5,2) DEFAULT NULL COMMENT '开模2流量(%)',
  `open_mold2_position` decimal(10,2) DEFAULT NULL COMMENT '开模2位置(mm)',
  `open_mold3_pressure` decimal(10,2) DEFAULT NULL COMMENT '开模3压力(bar)',
  `open_mold3_flow` decimal(5,2) DEFAULT NULL COMMENT '开模3流量(%)',
  `open_mold3_position` decimal(10,2) DEFAULT NULL COMMENT '开模3位置(mm)',
  `open_mold4_pressure` decimal(10,2) DEFAULT NULL COMMENT '开模4压力(bar)',
  `open_mold4_flow` decimal(5,2) DEFAULT NULL COMMENT '开模4流量(%)',
  `open_mold4_position` decimal(10,2) DEFAULT NULL COMMENT '开模4位置(mm)',
  `core_pull1_out_pressure` decimal(10,2) DEFAULT NULL COMMENT '抽芯一压力(bar)',
  `core_pull1_out_flow` decimal(5,2) DEFAULT NULL COMMENT '抽芯一流量(%)',
  `core_pull1_out_position` decimal(10,2) DEFAULT NULL COMMENT '抽芯一位置(mm)',
  `core_pull2_out_pressure` decimal(10,2) DEFAULT NULL COMMENT '抽芯二压力(bar)',
  `core_pull2_out_flow` decimal(5,2) DEFAULT NULL COMMENT '抽芯二流量(%)',
  `core_pull2_out_position` decimal(10,2) DEFAULT NULL COMMENT '抽芯二位置(mm)',
  `melt1_pressure` decimal(10,2) DEFAULT NULL COMMENT '熔胶1压力(bar)',
  `melt1_flow` decimal(5,2) DEFAULT NULL COMMENT '熔胶1流量(%)',
  `melt1_position` decimal(10,2) DEFAULT NULL COMMENT '熔胶1位置(mm)',
  `decompression_before_melt_pressure` decimal(10,2) DEFAULT NULL COMMENT '熔前松退压力(bar)',
  `decompression_before_melt_flow` decimal(5,2) DEFAULT NULL COMMENT '熔前松退流量(%)',
  `decompression_before_melt_position` decimal(10,2) DEFAULT NULL COMMENT '熔前松退位置(mm)',
  `decompression_after_melt_pressure` decimal(10,2) DEFAULT NULL COMMENT '熔后松退压力(bar)',
  `decompression_after_melt_flow` decimal(5,2) DEFAULT NULL COMMENT '熔后松退流量(%)',
  `decompression_after_melt_position` decimal(10,2) DEFAULT NULL COMMENT '熔后松退位置(mm)',
  `eject1_speed_pressure` decimal(10,2) DEFAULT NULL COMMENT '顶出一速压力(bar)',
  `eject1_speed_flow` decimal(5,2) DEFAULT NULL COMMENT '顶出一速流量(%)',
  `eject1_speed_position` decimal(10,2) DEFAULT NULL COMMENT '顶出一速位置(mm)',
  `eject2_speed_pressure` decimal(10,2) DEFAULT NULL COMMENT '顶出二速压力(bar)',
  `eject2_speed_flow` decimal(5,2) DEFAULT NULL COMMENT '顶出二速流量(%)',
  `eject2_speed_position` decimal(10,2) DEFAULT NULL COMMENT '顶出二速位置(mm)',
  `eject_retract1_speed_pressure` decimal(10,2) DEFAULT NULL COMMENT '顶退一速压力(bar)',
  `eject_retract1_speed_flow` decimal(5,2) DEFAULT NULL COMMENT '顶退一速流量(%)',
  `eject_retract1_speed_position` decimal(10,2) DEFAULT NULL COMMENT '顶退一速位置(mm)',
  `eject_retract2_speed_pressure` decimal(10,2) DEFAULT NULL COMMENT '顶退二速压力(bar)',
  `eject_retract2_speed_flow` decimal(5,2) DEFAULT NULL COMMENT '顶退二速流量(%)',
  `eject_retract2_speed_position` decimal(10,2) DEFAULT NULL COMMENT '顶退二速位置(mm)',
  
  -- 特殊模式参数
  `injection_mode` varchar(50) DEFAULT NULL COMMENT '注射模式',
  `core_pull_in_method` varchar(50) DEFAULT NULL COMMENT '进芯方式',
  `core_pull_out_method` varchar(50) DEFAULT NULL COMMENT '抽芯方式',
  `nozzle_contact_method` varchar(50) DEFAULT NULL COMMENT '座台方式',
  `ejection_mode` varchar(50) DEFAULT NULL COMMENT '顶针模式',
  `ejection_count` int DEFAULT NULL COMMENT '顶针次数',
  `screw_speed` decimal(10,2) DEFAULT NULL COMMENT '螺杆转速',
  `core_pull_stroke_method` varchar(50) DEFAULT NULL COMMENT '抽芯行程方式',
  
  -- 温度参数
  `barrel_temp1` decimal(5,2) DEFAULT NULL COMMENT '料筒温度第一段(℃)',
  `barrel_temp2` decimal(5,2) DEFAULT NULL COMMENT '料筒温度第二段(℃)',
  `barrel_temp3` decimal(5,2) DEFAULT NULL COMMENT '料筒温度第三段(℃)',
  `barrel_temp4` decimal(5,2) DEFAULT NULL COMMENT '料筒温度第四段(℃)',
  `mold_temp` decimal(5,2) DEFAULT NULL COMMENT '模具温度(℃)',
  
  -- 时间参数
  `clamping_time` decimal(10,2) DEFAULT NULL COMMENT '合模时间(s)',
  `mold_protection_time` decimal(10,2) DEFAULT NULL COMMENT '模保时间(s)',
  `core_pull1_in_time` decimal(10,2) DEFAULT NULL COMMENT '进芯1时间(s)',
  `core_pull2_in_time` decimal(10,2) DEFAULT NULL COMMENT '进芯2时间(s)',
  `injection_time` decimal(10,2) DEFAULT NULL COMMENT '注射时间(s)',
  `holding_time` decimal(10,2) DEFAULT NULL COMMENT '保压时间(s)',
  `cooling_time` decimal(10,2) DEFAULT NULL COMMENT '冷却时间(s)',
  `core_pull1_out_time` decimal(10,2) DEFAULT NULL COMMENT '抽芯1时间(s)',
  `core_pull2_out_time` decimal(10,2) DEFAULT NULL COMMENT '抽芯2时间(s)',
  `mold_opening_time` decimal(10,2) DEFAULT NULL COMMENT '开模时间(s)',
  `part_ejection_time` decimal(10,2) DEFAULT NULL COMMENT '取件时间(s)',
  `total_time` decimal(10,2) DEFAULT NULL COMMENT '总时间(s)',
  
  -- 原材料干燥处理
  `drying_equipment` varchar(200) DEFAULT NULL COMMENT '干燥使用设备',
  `material_fill_height` decimal(10,2) DEFAULT NULL COMMENT '盛料高度',
  `material_turning_time` decimal(10,2) DEFAULT NULL COMMENT '翻料时间',
  `drying_temp` decimal(5,2) DEFAULT NULL COMMENT '干燥温度',
  `front_mold_cooling` varchar(200) DEFAULT NULL COMMENT '前模冷却',
  
  -- 零件后处理
  `part_post_treatment` varchar(500) DEFAULT NULL COMMENT '零件后处理',
  `product_post_treatment` varchar(500) DEFAULT NULL COMMENT '产品后处理',
  `heating_temp` decimal(5,2) DEFAULT NULL COMMENT '加热温度',
  `holding_temp` decimal(5,2) DEFAULT NULL COMMENT '保温温度',
  `drying_time` decimal(10,2) DEFAULT NULL COMMENT '干燥时间',
  `rear_mold_cooling` varchar(200) DEFAULT NULL COMMENT '后模冷却',
  
  -- 工序内容和品质检查
  `process_content` text COMMENT '工序内容',
  `quality_inspection` text COMMENT '品质检查',
  `comprehensive_assessment` text COMMENT '模具及注塑工艺综合评估',
  
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint DEFAULT 0 COMMENT '删除标志：0-未删除，1-已删除',
  
  PRIMARY KEY (`id`),
  KEY `idx_file_id` (`file_id`),
  KEY `idx_file_no` (`file_no`),
  KEY `idx_equipment_id` (`equipment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工艺文件详细内容表';
